import { StyleSheet, Dimensions } from "react-native";
import Constants from 'expo-constants';
let ScreenHeight = Dimensions.get("window").height;
let ScreenWidth = Dimensions.get("window").width;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    height: ScreenHeight,
  },
  map: {
    width: ScreenWidth,
    height: "100%",
  },
  searchContainer: {
    position: 'absolute',
    top: 20,
    left: ScreenWidth * 0.05,
    width: "90%",
    backgroundColor: "white",
    shadowColor: "black",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.5,
    elevation: 4,
    padding: 8,
    borderRadius: 8,
  },
  input: {
    borderColor: "#888",
    borderWidth: 1,
  },
  center: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 50,
    height: 50,
    borderRadius: 50,
    elevation: 5,
    zIndex: 100,
    backgroundColor: "red",
  },
  centerImage: {
    width: 50,
    height: 50,
    borderRadius: 50,
  },
  bottomPopupContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    paddingHorizontal: 30,
    paddingVertical: 20,
    width: ScreenWidth,
    height: "auto",
    elevation: 5,
    zIndex: 100,
    backgroundColor: "white",
    display: "flex",
    alignItems: "stretch",
    justifyContent: "center",
    maxHeight : ScreenHeight * 0.4,
  },
  sliderMark: {
    width: 20,
    height: 20,
    backgroundColor: "#DDDDDD",
    borderRadius: 20,
  },
  nextButton: {
    position: 'absolute',
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    bottom: 90,
    right: 20,
    width: 50,
    height: 50,
    borderRadius: 50,
    elevation: 5,
    zIndex: 1000,
    backgroundColor: "white",
  },
  nextButtonImage: {
    width: 40,
    height: 40,
    borderRadius: 40,
  },
  button: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "white",
    fontSize: 20,
  },
  routeOption: {
    width: "100%",
    padding: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  RouteFormat : {
    borderBottomColor: "#DDD",
    borderBottomWidth: 1,
    paddingRight: 10,
  },
  borderBottom: {
    borderBottomColor: "#DDD",
    borderBottomWidth: 1,
  },
  routeOptionPrice: {
    color: "black",
    fontSize: 20,
    fontWeight: "bold",
  },
  routeOptionInformation: {
    display: "flex",
    alignItems: "flex-start",
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  routeOptionTrips: {
    width: "70%",
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
  },
  routeOptionTripText: {
    fontSize: 20,
    fontWeight: "bold",
    paddingRight: 10,
    paddingLeft: 5,
  },
  scrollViewBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: ScreenWidth,
    maxHeight: ScreenHeight * 0.4,
    backgroundColor: "white",
    zIndex: 1000,
  },
  flex: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 0
  },
  subRides: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingBottom: 20,
    paddingTop: 0,
  },
  subRideText: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 20,
  },
  subRideTextDestination: {
    fontSize: 20,
    fontWeight: "bold",
  },
  subRideTextTime: {
    fontSize: 20,
    color: "#DDD",
  },
  bookSeatsText: {
    fontSize: 14,
    color: "black",
  },
});